// Kitchen items data
// Items are automatically generated from images in the images folder

const kitchenItems = [
    { name: "Blue Rectangle Lid", category: "storage", image: "images/Item-1.jpeg", quantity: 1, location: "bin bag", description: "translucent light blue rectangular plastic lid" },
    { name: "Costa Thermal Mug", category: "drink", image: "images/Item-2.jpeg", quantity: 1, location: "bin bag", description: "costa coffee branded stainless steel thermal travel mug" },
    { name: "Yellow Silicone Lid", category: "drink", image: "images/Item-3.jpeg", quantity: 1, location: "bin bag", description: "yellow silicone coffee cup lid" },
    { name: "Orange Rectangle Lid", category: "storage", image: "images/Item-4.jpeg", quantity: 1, location: "bin bag", description: "orange rectangular plastic lid" },
    { name: "Huel Shaker Bottle", category: "drink", image: "images/Item-5.jpeg", quantity: 1, location: "bin bag", description: "huel branded shaker bottle" },
    { name: "Ziland Water Bottle", category: "drink", image: "images/Item-6.jpeg", quantity: 1, location: "bin bag", description: "ziland branded black water bottle" },
    { name: "Blue Plate", category: "tableware", image: "images/Item-7.jpeg", quantity: 1, location: "bin bag", description: "translucent blue plastic plate" },
    { name: "Graduated Measuring Cup", category: "tools", image: "images/Item-8.jpeg", quantity: 1, location: "bin bag", description: "clear plastic measuring cup with graduated markings" },
    { name: "Large Storage Lid", category: "storage", image: "images/Item-9.jpeg", quantity: 1, location: "bin bag", description: "large semi-clear rectangular plastic storage lid" },
    { name: "4-Lock Leak-Proof Lid", category: "storage", image: "images/Item-10.jpeg", quantity: 1, location: "bin bag", description: "fresh keeping 4-lock design leak-proof lid" },
    { name: "White Rectangle Lid", category: "storage", image: "images/Item-11.jpeg", quantity: 1, location: "bin bag", description: "white rectangular plastic lid" },
    { name: "Square Food Container", category: "storage", image: "images/Item-12.jpeg", quantity: 1, location: "bin bag", description: "square semi-clear plastic food container" },
    { name: "Green Square Lid", category: "storage", image: "images/Item-13.jpeg", quantity: 1, location: "bin bag", description: "green square plastic lid" },
    { name: "White Utility Tray", category: "storage", image: "images/Item-14.jpeg", quantity: 1, location: "bin bag", description: "rectangular white plastic tray or lid" },
    { name: "Grey Rectangle Lid", category: "storage", image: "images/Item-15.jpeg", quantity: 1, location: "bin bag", description: "grey rectangular plastic lid" },
    { name: "Textured Orange Lid", category: "storage", image: "images/Item-16.jpeg", quantity: 1, location: "bin bag", description: "orange rectangular plastic lid with textured surface" },
    { name: "Waffle/Nut Maker", category: "appliances", image: "images/Item-17.jpeg", quantity: 1, location: "box on shelves", description: "electric waffle or nut maker appliance" },
    { name: "Narrow Clear Lid", category: "misc", image: "images/Item-18.jpeg", quantity: 1, location: "bin bag", description: "long, narrow clear plastic lid" },
    { name: "Blue Square Lid", category: "storage", image: "images/Item-19.jpeg", quantity: 1, location: "bin bag", description: "blue square plastic lid" },
    { name: "Silicone Baking Mat", category: "bakeware", image: "images/Item-20.jpeg", quantity: 1, location: "bin bag", description: "red rectangular textured silicone baking mat" },
    { name: "Clear Storage Lid", category: "storage", image: "images/Item-21.jpeg", quantity: 1, location: "bin bag", description: "Rectangular clear plastic lid for a food storage container." },
    { name: "Mini Cupcake Maker", category: "appliances", image: "images/Item-22.jpeg", quantity: 1, location: "box on shelves", description: "Electric mini cupcake or muffin maker with seven circular wells." },
    { name: "Hommer Crepe Maker", category: "appliances", image: "images/Item-23.jpeg", quantity: 1, location: "box on shelves", description: "Electric crepe maker or pancake griddle (Hommer brand)." },
    { name: "Orange Circular Lid", category: "storage", image: "images/Item-24.jpeg", quantity: 1, location: "bin bag", description: "Circular orange plastic lid for a food storage container." },
    { name: "Orange Plastic Basket", category: "storage", image: "images/Item-25.jpeg", quantity: 2, location: "bin bag", description: "Rectangular orange plastic basket or laundry caddy." },
    { name: "Lime Circular Lid", category: "storage", image: "images/Item-26.jpeg", quantity: 1, location: "bin bag", description: "Circular lime green plastic lid for a food storage container." },
    { name: "Fridge Egg Tray", category: "misc", image: "images/Item-27.jpeg", quantity: 1, location: "bin bag", description: "Clear plastic egg holder tray for a refrigerator." },
    { name: "Green Plastic Colander", category: "prep", image: "images/Item-28.jpeg", quantity: 1, location: "bin bag", description: "Light green plastic colander or strainer bowl." },
    { name: "Mini Food Container", category: "storage", image: "images/Item-29.jpeg", quantity: 1, location: "bin bag", description: "Small rectangular clear plastic food container." },
    { name: "Plastic Wine Glasses", category: "drink", image: "images/Item-30.jpeg", quantity: 1, location: "bin bag", description: "Disassembled plastic wine glasses (two bowls and three bases)." },
    { name: "Pirate Plate", category: "tableware", image: "images/Item-31.jpeg", quantity: 1, location: "bin bag", description: "An octagonal plastic plate featuring a \"Pirates of the Caribbean\" design." },
    { name: "Microwave Safe Lid", category: "storage", image: "images/Item-32.jpeg", quantity: 1, location: "bin bag", description: "A rectangular translucent plastic lid for a food container, labeled \"Microwave Safe.\"" },
    { name: "4-Tab Locking Lid", category: "storage", image: "images/Item-33.jpeg", quantity: 1, location: "bin bag", description: "A rectangular clear plastic locking lid with four side tabs." },
    { name: "Blue Seal Locking Lid", category: "storage", image: "images/Item-34.jpeg", quantity: 1, location: "bin bag", description: "A rectangular plastic locking lid featuring a blue silicone seal and four side tabs." },
    { name: "Jaguar/Land Rover Bottle", category: "drink", image: "images/Item-35.jpeg", quantity: 1, location: "bin bag", description: "A translucent plastic water bottle with a lime green cap, branded with Land Rover and Jaguar logos." },
    { name: "Striped Popcorn Bucket", category: "misc", image: "images/Item-36.jpeg", quantity: 1, location: "bin bag", description: "A tall, rectangular plastic popcorn bucket with classic red and white stripes." },
    { name: "Flip-Top Storage Bin", category: "storage", image: "images/Item-37.jpeg", quantity: 1, location: "bin bag", description: "A large clear plastic storage container with a blue flip-top lid." },
    { name: "Manual Pasta Maker", category: "appliances", image: "images/Item-38.jpeg", quantity: 1, location: "box on shelves", description: "A heavy-duty stainless steel manual pasta maker machine." },
    { name: "Embossed Octagonal Serving Bowl", category: "serveware", image: "images/Item-101.jpeg", quantity: 1, location: "Box 2", description: "An octagonal white ceramic serving bowl featuring a decorative raised scroll pattern around the rim." },
    { name: "Round Glass Casserole Dish", category: "bakeware", image: "images/Item-102.jpeg", quantity: 2, location: "Box 2", description: "A shallow, circular clear glass baking dish with two small integrated handles for easy gripping." },
    { name: "Oval Glass Roasting Dish", category: "bakeware", image: "images/Item-103.jpeg", quantity: 1, location: "Box 2", description: "A clear, oval-shaped glass dish designed with raised handles on the short ends, typically used for roasting or baking." },
    { name: "Oval Glass Serving Dish", category: "serveware", image: "images/Item-104.jpeg", quantity: 1, location: "Box 2", description: "A deep, oval clear glass bowl that includes textured, non-slip handles at the base of each end." },
    { name: "Fruit-Bordered Oval Platter", category: "serveware", image: "images/Item-105.jpeg", quantity: 1, location: "Box 2", description: "A classic white ceramic oval platter decorated with a detailed raised fruit and vine border." },
    { name: "Square Pedestal Cake Stand", category: "serveware", image: "images/Item-106.jpeg", quantity: 2, location: "Box 1", description: "A modern, square white pedestal stand with a slightly concave surface and beaded edges." },
    { name: "Faux-Bamboo Rectangular Tray", category: "serveware", image: "images/Item-107.jpeg", quantity: 2, location: "box on shelves", description: "A rectangular white ceramic tray with a distinctive scalloped rim that mimics the look of bamboo." },
    { name: "Decorative Handled Serving Tray", category: "serveware", image: "images/Item-108.jpeg", quantity: 2, location: "box on shelves", description: "A large, flat white ceramic serving tray accented with elegant flourishes on the top and bottom handles." },
    { name: "White Oval Baking Dish", category: "bakeware", image: "images/Item-109.jpeg", quantity: 1, location: "Box 3", description: "A simple, deep oval ceramic dish in plain white, perfect for baking or serving side dishes." },
    { name: "Textured Geometric Serving Plate", category: "serveware", image: "images/Item-110.jpeg", quantity: 1, location: "Box 1", description: "A wide, circular white plate featuring a complex geometric hobnail or starburst texture across its entire surface." },
    { name: "Scalloped Glass Petal Bowl", category: "serveware", image: "images/Item-111.jpeg", quantity: 2, location: "Box 1", description: "A clear glass serving bowl featuring a fluid, petal-like design that creates a ruffled silhouette." },
    { name: "Navette Serving Boat", category: "serveware", image: "images/Item-112.jpeg", quantity: 2, location: "Box 2", description: "A long, slender white ceramic dish with pointed ends, resembling a minimalist boat shape." },
    { name: "Contemporary Long Serving Tray", category: "serveware", image: "images/Item-113.jpeg", quantity: 2, location: "Box 2", description: "A narrow, rectangular white porcelain platter with elegantly curved short edges." },
    { name: "Scalloped Square Casserole Dish", category: "bakeware", image: "images/Item-114.jpeg", quantity: 2, location: "Box 3", description: "A deep, square white ceramic baking dish distinguished by its wavy, scalloped rim and integrated side handles." },
    { name: "Instant Coffee Jar", category: "canisters", image: "images/Item-115.jpeg", quantity: 2, location: "Box 3", description: "A tall glass jar containing Nescafe Gold Blend instant coffee, topped with a signature gold-toned lid." },
    { name: "Utility Glass Canister", category: "canisters", image: "images/Item-116.jpeg", quantity: 1, location: "Box 3", description: "A standard clear glass storage jar with a simple white screw-on plastic cap." },
    { name: "Globe Glass Storage Jar", category: "canisters", image: "images/Item-117.jpeg", quantity: 1, location: "Box 3", description: "A round, spherical clear glass jar with a flat base and a brushed metal screw-top lid." },
    { name: "Glass Preserve Jar", category: "canisters", image: "images/Item-118.jpeg", quantity: 1, location: "Box 3", description: "A classic clear glass mason-style jar without a lid, showing the threaded rim for a screw-on top." },
    { name: "Labeled Sugar Canister", category: "canisters", image: "images/Item-119.jpeg", quantity: 3, location: "Box 3", description: "A tall, cylindrical glass canister featuring a metal lid and a decorative metal label embossed with the word \"SUGAR.\"" },
    { name: "Mini Glass Spice Jar", category: "condiments", image: "images/Item-120.jpeg", quantity: 3, location: "Box 3", description: "A small, squat glass spice or condiment jar with a polished silver-toned lid." },
    { name: "Small Glass Bowl with Orange Lid", category: "canisters", image: "images/Item-121.jpeg", quantity: 1, location: "Box 3", description: "A clear, round glass container featuring a matching flexible orange plastic lid for airtight storage." },
    { name: "Small Glass Bowl", category: "serveware", image: "images/Item-122.jpeg", quantity: 1, location: "Box 3", description: "A simple, transparent round glass bowl typically used for prep work, dips, or small servings." },
    { name: "Cholula Hot Sauce Bottle", category: "condiments", image: "images/Item-123.jpeg", quantity: 1, location: "Box 3", description: "An empty 150 ml glass bottle of Cholula Original hot sauce, recognizable by its iconic wooden cap and yellow label." },
    { name: "Plastic Egg Tray", category: "misc", image: "images/Item-124.jpeg", quantity: 1, location: "Box 3", description: "A clear, rectangular plastic organizer designed with individual circular divots to hold up to twelve eggs securely in a refrigerator." },
    { name: "Ceramic Casserole Dish with Lid", category: "bakeware", image: "images/Item-125.jpeg", quantity: 1, location: "Box 3", description: "A sturdy white ceramic casserole dish with integrated side handles and a matching rounded lid for oven-to-table use." },
    { name: "Glass Serving Tray with Metal Handles", category: "serveware", image: "images/Item-126.jpeg", quantity: 1, location: "Box 3", description: "A circular, flat glass platter featuring decorative etched lines and two curved silver metal handles for easy carrying." }
];
